[bar]
order = "main"

[bar.default]
position = "top"
panel_overlap = 10
radius = 10
start = [
    "clock",
    "neuro/upbeat:upbeat",
    "taskbar",
    "privacy",
    "weather",
]
center = ["active_window"]
end = [
    "media",
    "andrewdems/printers:printer",
    "lock_keys",
    "tray",
    "keyboard_layout",
    "network",
    "bluetooth",
    "dotnetrob/cat:cat",
    "brightness",
    "volume",
    "volume-mic",
    "battery",
]

[widget.taskbar]
icon_scale = 1.3
group_by_workspace = true
show_workspace_label = false
hide_empty_workspaces = true
workspace_group_capsule = false

[widget.privacy]
hide_inactive = true
active_color = "error"

[widget.active_window.actions]
left = "panel-toggle control-center"

[widget.media]
title_scroll = "always"

[widget.tray]
drawer = true

[widget.keyboard_layout]
show_glyph = false

[widget."dotnetrob/cat:cat"]
font_scale = 1.35
show_cpu_percent = true
cat_color_mode = "custom"
cat_color = "#ffffff"

[widget."dotnetrob/cat:cat".actions]
left = "panel-toggle control-center system"

[widget.volume.actions]
scroll_up = "volume-up 1%"
scroll_down = "volume-down 1%"

[widget.volume-mic]
type = "volume"
device = "input"
# hide_when_inactive = true

[widget.volume-mic.actions]
scroll_up = "volume-up 1%"
scroll_down = "volume-down 1%"

[widget.clock]
format = "%H:%M:%S"

[widget.clock.actions]
right = "exec notion-calendar-electron"
